name: Release Docs

on:
  push:
    tags:
      - "v*"
    branches:
      - main

jobs:
  release_docs:
    name: Release Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "./docs/scripts/requirements.txt"
      - run: |
          pip install -r docs/scripts/requirements.txt
      - name: setup
        run: |
          ./docs/scripts/copy-docs.sh
      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: build and push
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          mike deploy ${{ github.ref_name }} latest --push --update-aliases
          mike set-default --push latest
      - name: build and push
        if: startsWith(github.ref, 'refs/heads/')
        run: |
          mike deploy dev --push --update-aliases
          mike set-default --push dev
